Add a method for logging warnings
openflighthpc/flight_configuration pull request #2
Opened 2021-06-11 16:40 UTC by WilliamMcCumstie

A `log_warning` method has been added to the configuration DSL. It processes the `__sources__` struct and logs the missing keys.

It relies on the application setting the `Flight.config` and `Flight.logger` stubs. This way the `config` can be loaded and `logger` configured beforehand.

2021-06-15 10:25 UTC, benarmston requested changes
This works well.  I have a few comments for you to look at.

2021-06-15 10:25 UTC, benarmston commented on lib/flight_configuration/base_dsl.rb
> +  SourceStruct = Struct.new(:key, :source, :type, :value, :missing)
IIUC `missing` means that a value has been provided in the config file, that is not a known setting.

In my initial reading of this I thought that `missing` meant that a known setting was missing (did not have a value provided).

A better name for this would be `unrecognized`, `unknown`, `unknown_setting`, `additional`?

2021-06-15 10:25 UTC, benarmston commented on lib/flight_configuration/base_dsl.rb
> +        Flight.logger.warn "Ignoring undefined config '#{key}' (source: #{source.source})"
Change `undefined` to `unrecognized`.

2021-06-16 12:48 UTC, WilliamMcCumstie commented on lib/flight_configuration/base_dsl.rb
> +  SourceStruct = Struct.new(:key, :source, :type, :value, :missing)
https://github.com/openflighthpc/flight_configuration/pull/2/commits/b6935ee070bbc26625699ff44796666d8aab5447

2021-06-16 12:48 UTC, WilliamMcCumstie commented on lib/flight_configuration/base_dsl.rb
> +        Flight.logger.warn "Ignoring undefined config '#{key}' (source: #{source.source})"
Updated

2021-06-16 12:49 UTC, WilliamMcCumstie commented
As discussed, `FlightConfiguration` no longer integrates with `Flight.logger` directly. This prevents circular references.

Instead it creates a `hash` which contains the various messages it would otherwise log. Whilst doing so, it was fairly trivial to add some additional `info`/`debug` logs.

2021-06-17 12:26 UTC, benarmston commented
I've added a couple of commits to change the details of the logging.  In brief, they are now collected whilst loading the configuration not afterwards.  There is also a simpler API for the application to log the logs.

2021-06-17 12:33 UTC, WilliamMcCumstie commented
LGTM

2021-06-17 12:39 UTC, merged